import { useState } from "react";
import styles from '../styles/Home.module.scss'
import Head from 'next/head'
import { Footer } from '../src/components/footer'
import { Header } from '../src/components/header'
import { WelcomeSection } from '../src/section/welcomeSection'
import { ProjectsWeb } from '../src/section/projectsWeb'
import { ProjectsMobile } from '../src/section/projectsMobile'
import { Tech } from '../src/section/tech/tech'
import { AboutMe } from '../src/section/aboutMe'
import { BsWhatsapp } from "react-icons/bs"

export default function Home() {

  const [selectSection, setSelectSection] = useState(false)
   
  
  return (
    <>
      <Head>
        <title>Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.container}>
        <Header />
        <main className={styles.main}>

          <WelcomeSection 
          setSelectSection={setSelectSection}
          />


          { selectSection ?
          <ProjectsWeb 
          
          />
          :
          <ProjectsMobile/>
}
          <Tech />

          <AboutMe />
        </main>
      </div>
      <a href="https://wa.me/5516988210069">
        <BsWhatsapp size={40} className={styles.iconWhats} />
      </a>
      <Footer />
    </>
  )
}
