import styles from '../styles/Home.module.scss'
import Head from 'next/head'
import { Footer } from '../src/components/footer'
import { Header } from '../src/components/header'
import { WelcomeSection } from '../src/section/welcomeSection'
import { Projects } from '../src/section/projects'
import { Tech } from '../src/section/tech/tech'
import { AboutMe } from '../src/section/aboutMe'

export default function Home() {
  return (
    <>
    <Head>
        <title>Portifólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    <div className={styles.container}>
      <Header/>
      <main className={styles.main}>
    
      <WelcomeSection/>
    
      <Projects/>

      <Tech/>
      <AboutMe/>

      </main>

    
    </div>
    <Footer/>
    </>
  )
}
